In [1]:
pip install numpy pandas nltk

Requirement already satisfied: numpy in c:\users\syed junaid ali shah\appdata\local\programs\python\python313\lib\site-packages (2.3.1)
Requirement already satisfied: pandas in c:\users\syed junaid ali shah\appdata\local\programs\python\python313\lib\site-packages (2.3.0)
Requirement already satisfied: nltk in c:\users\syed junaid ali shah\appdata\local\programs\python\python313\lib\site-packages (3.9.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\syed junaid ali shah\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\syed junaid ali shah\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\syed junaid ali shah\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: click in c:\users\syed junaid ali shah\appdata\local\programs\python\python313\lib\site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in c:\users\syed junaid ali shah\appdata\local\programs\python\python313\lib\site-packages (from nltk) (1.5.1)
Requirement already satisfied: regex>=2021.8.3 in c:\users\syed junaid ali shah\appdata\local\programs\python\python313\lib\site-packages (from nltk) (2025.7.34)
Requirement already satisfied: tqdm in c:\users\syed junaid ali shah\appdata\local\programs\python\python313\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: six>=1.5 in c:\users\syed junaid ali shah\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: colorama in c:\users\syed junaid ali shah\appdata\local\programs\python\python313\lib\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [4]:
# Import Modules

import pandas as pd
import numpy as np
import re
import nltk
pd.set_option('display.max_columns', None)

In [5]:
df = pd.read_csv('IMDB_OMDB_Kaggle_TestSet_OMDB_Detailed.csv')
df.head()

,Unnamed: 0,Title,Year,Rated,Released,Runtime,Genre,Director,Writer,Actors,Plot,Language,Country,Awards,Poster,Ratings.Source,Ratings.Value,Metascore,imdbRating,imdbVotes,imdbID,Type,tomatoMeter,tomatoImage,tomatoRating,tomatoReviews,tomatoFresh,tomatoRotten,tomatoConsensus,tomatoUserMeter,tomatoUserRating,tomatoUserReviews,tomatoURL,DVD,BoxOffice,Production,Website,Response
0,1,Avatar,2009,PG-13,18 Dec 2009,162 min,"Action, Adventure, Fantasy",James Cameron,James Cameron,"Sam Worthington, Zoe Saldana, Sigourney Weaver...",A paraplegic marine dispatched to the moon Pan...,"English, Spanish","UK, USA",Won 3 Oscars. Another 86 wins & 128 nominations.,https://images-na.ssl-images-amazon.com/images...,Internet Movie Database,7.8/10,83,7.8,"939,525",tt0499549,movie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/avatar/,22 Apr 2010,"$749,700,000",20th Century Fox,http://www.avatarmovie.com/,True
1,2,Pirates of the Caribbean: At World's End,2007,PG-13,25 May 2007,169 min,"Action, Adventure, Fantasy",Gore Verbinski,"Ted Elliott, Terry Rossio, Ted Elliott (charac...","Johnny Depp, Geoffrey Rush, Orlando Bloom, Kei...","Captain Barbossa, Will Turner and Elizabeth Sw...",English,USA,Nominated for 2 Oscars. Another 20 wins & 44 n...,https://images-na.ssl-images-amazon.com/images...,Internet Movie Database,7.1/10,50,7.1,"506,076",tt0449088,movie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/pirates_of_the...,04 Dec 2007,"$309,404,152",Buena Vista,http://disney.go.com/disneypictures/pirates/at...,True
2,3,Spectre,2015,PG-13,06 Nov 2015,148 min,"Action, Adventure, Thriller",Sam Mendes,"John Logan (screenplay), Neal Purvis (screenpl...","Daniel Craig, Christoph Waltz, Léa Seydoux, Ra...",A cryptic message from Bond's past sends him o...,"English, Spanish, Italian, German, French","UK, USA",Won 1 Oscar. Another 7 wins & 30 nominations.,https://images-na.ssl-images-amazon.com/images...,Internet Movie Database,6.8/10,60,6.8,"311,366",tt2379713,movie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/spectre_2015/,09 Feb 2016,"$208,777,731",Sony Pictures,http://www.007.com/,True
3,4,The Dark Knight Rises,2012,PG-13,20 Jul 2012,164 min,"Action, Thriller",Christopher Nolan,"Jonathan Nolan (screenplay), Christopher Nolan...","Christian Bale, Gary Oldman, Tom Hardy, Joseph...",Eight years after the Joker's reign of anarchy...,"English, Arabic","UK, USA",Nominated for 1 BAFTA Film Award. Another 38 w...,https://images-na.ssl-images-amazon.com/images...,Internet Movie Database,8.5/10,78,8.5,"1,228,378",tt1345836,movie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/the_dark_knigh...,03 Dec 2012,"$448,130,642",Warner Bros. Pictures,http://www.thedarkknightrises.com/,True
4,5,The Lone Ranger,2013,PG-13,03 Jul 2013,150 min,"Action, Adventure, Western",Gore Verbinski,"Justin Haythe (screenplay), Ted Elliott (scree...","Johnny Depp, Armie Hammer, William Fichtner, T...",Native American warrior Tonto recounts the unt...,"English, North American Indian",USA,Nominated for 2 Oscars. Another 4 wins & 17 no...,https://images-na.ssl-images-amazon.com/images...,Internet Movie Database,6.5/10,37,6.5,"191,532",tt1210819,movie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/the_lone_ranger/,17 Dec 2013,"$89,289,910",Walt Disney Pictures,http://disney.go.com/the-lone-ranger/,True

In [ ]:
df['Plot'][4]

In [7]:

##Data Preprocessing: Lowercase, remove punctuation, and normalize spaces
df['Clean_plot'] = df['Plot'].str.lower()
df['Clean_plot'] = df['Clean_plot'].apply(lambda x: re.sub(r'[^a-zA-Z]', ' ', x))
df['Clean_plot'] = df['Clean_plot'].apply(lambda x: re.sub(r'\s+', ' ', x))

In [11]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to C:\Users\Syed Junaid Ali
[nltk_data]     Shah\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to C:\Users\Syed Junaid Ali
[nltk_data]     Shah\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [10]:
##Tokeniza the Sentence

import nltk
nltk.download('punkt', force=True)
nltk.download('punkt_tab', force=True)  # Add this line

from nltk.tokenize import word_tokenize

df['Clean_plot'] = df['Clean_plot'].apply(lambda x: word_tokenize(x))
df['Clean_plot']

[nltk_data] Downloading package punkt to C:\Users\Syed Junaid Ali
[nltk_data]     Shah\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package punkt_tab to C:\Users\Syed Junaid Ali
[nltk_data]     Shah\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

0     [a, paraplegic, marine, dispatched, to, the, m...
1     [captain, barbossa, will, turner, and, elizabe...
2     [a, cryptic, message, from, bond, s, past, sen...
3     [eight, years, after, the, joker, s, reign, of...
4     [native, american, warrior, tonto, recounts, t...
5     [transported, to, barsoom, a, civil, war, vet,...
6     [the, magically, long, haired, rapunzel, has, ...
7     [a, strange, black, entity, from, another, wor...
8     [when, tony, stark, and, bruce, banner, try, t...
9     [political, interference, in, the, avengers, a...
10    [fearing, that, the, actions, of, superman, ar...
11    [a, reluctant, hobbit, bilbo, baggins, sets, o...
12    [as, harry, potter, begins, his, sixth, year, ...
13    [the, dwarves, along, with, bilbo, baggins, an...
14    [bilbo, and, company, are, forced, to, engage,...
15    [jack, sparrow, and, barbossa, embark, on, a, ...
16    [superman, reappears, after, a, long, absence,...
17    [james, bond, descends, into, mystery, as, he,...
18    [earth, s, mightiest, heroes, must, come, toge...
19    [jack, sparrow, races, to, recover, the, heart...
20    [clark, kent, one, of, the, last, of, an, exti...
21    [the, pevensie, siblings, return, to, narnia, ...
22    [after, peter, parker, is, bitten, by, a, gene...
23    [a, new, theme, park, built, on, the, original...
Name: Clean_plot, dtype: object

In [17]:
# Remove Stopwords

import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')  # Only needed once

stop_words = stopwords.words('english')
plot = []

for sentence in df['Clean_plot']:
    temp = []
    for word in sentence:
        if word not in stop_words and len(word) >= 3:
            temp.append(word)
    plot.append(temp)

plot  # This will contain your cleaned, tokenized plots

[nltk_data] Downloading package stopwords to C:\Users\Syed Junaid Ali
[nltk_data]     Shah\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

[['paraplegic',
  'marine',
  'dispatched',
  'moon',
  'pandora',
  'unique',
  'mission',
  'becomes',
  'torn',
  'following',
  'orders',
  'protecting',
  'world',
  'feels',
  'home'],
 ['captain',
  'barbossa',
  'turner',
  'elizabeth',
  'swann',
  'must',
  'sail',
  'edge',
  'map',
  'navigate',
  'treachery',
  'betrayal',
  'find',
  'jack',
  'sparrow',
  'make',
  'final',
  'alliances',
  'one',
  'last',
  'decisive',
  'battle'],
 ['cryptic',
  'message',
  'bond',
  'past',
  'sends',
  'trail',
  'uncover',
  'sinister',
  'organization',
  'battles',
  'political',
  'forces',
  'keep',
  'secret',
  'service',
  'alive',
  'bond',
  'peels',
  'back',
  'layers',
  'deceit',
  'reveal',
  'terrible',
  'truth',
  'behind',
  'spectre'],
 ['eight',
  'years',
  'joker',
  'reign',
  'anarchy',
  'dark',
  'knight',
  'help',
  'enigmatic',
  'selina',
  'forced',
  'imposed',
  'exile',
  'save',
  'gotham',
  'city',
  'edge',
  'total',
  'annihilation',
  'brutal',
  'guerrilla',
  'terrorist',
  'bane'],
 ['native',
  'american',
  'warrior',
  'tonto',
  'recounts',
  'untold',
  'tales',
  'transformed',
  'john',
  'reid',
  'man',
  'law',
  'legend',
  'justice'],
 ['transported',
  'barsoom',
  'civil',
  'war',
  'vet',
  'discovers',
  'barren',
  'planet',
  'seemingly',
  'inhabited',
  'foot',
  'tall',
  'barbarians',
  'finding',
  'prisoner',
  'creatures',
  'escapes',
  'encounter',
  'woola',
  'princess',
  'desperate',
  'need',
  'savior'],
 ['magically',
  'long',
  'haired',
  'rapunzel',
  'spent',
  'entire',
  'life',
  'tower',
  'runaway',
  'thief',
  'stumbled',
  'upon',
  'discover',
  'world',
  'first',
  'time',
  'really'],
 ['strange',
  'black',
  'entity',
  'another',
  'world',
  'bonds',
  'peter',
  'parker',
  'causes',
  'inner',
  'turmoil',
  'contends',
  'new',
  'villains',
  'temptations',
  'revenge'],
 ['tony',
  'stark',
  'bruce',
  'banner',
  'try',
  'jump',
  'start',
  'dormant',
  'peacekeeping',
  'program',
  'called',
  'ultron',
  'things',
  'horribly',
  'wrong',
  'earth',
  'mightiest',
  'heroes',
  'stop',
  'villainous',
  'ultron',
  'enacting',
  'terrible',
  'plan'],
 ['political',
  'interference',
  'avengers',
  'activities',
  'causes',
  'rift',
  'former',
  'allies',
  'captain',
  'america',
  'iron',
  'man'],
 ['fearing',
  'actions',
  'superman',
  'left',
  'unchecked',
  'batman',
  'takes',
  'man',
  'steel',
  'world',
  'wrestles',
  'kind',
  'hero',
  'really',
  'needs'],
 ['reluctant',
  'hobbit',
  'bilbo',
  'baggins',
  'sets',
  'lonely',
  'mountain',
  'spirited',
  'group',
  'dwarves',
  'reclaim',
  'mountain',
  'home',
  'gold',
  'within',
  'dragon',
  'smaug'],
 ['harry',
  'potter',
  'begins',
  'sixth',
  'year',
  'hogwarts',
  'discovers',
  'old',
  'book',
  'marked',
  'property',
  'half',
  'blood',
  'prince',
  'begins',
  'learn',
  'lord',
  'voldemort',
  'dark',
  'past'],
 ['dwarves',
  'along',
  'bilbo',
  'baggins',
  'gandalf',
  'grey',
  'continue',
  'quest',
  'reclaim',
  'erebor',
  'homeland',
  'smaug',
  'bilbo',
  'baggins',
  'possession',
  'mysterious',
  'magical',
  'ring'],
 ['bilbo',
  'company',
  'forced',
  'engage',
  'war',
  'array',
  'combatants',
  'keep',
  'lonely',
  'mountain',
  'falling',
  'hands',
  'rising',
  'darkness'],
 ['jack',
  'sparrow',
  'barbossa',
  'embark',
  'quest',
  'find',
  'elusive',
  'fountain',
  'youth',
  'discover',
  'blackbeard',
  'daughter'],
 ['superman',
  'reappears',
  'long',
  'absence',
  'challenged',
  'old',
  'foe',
  'uses',
  'kryptonian',
  'technology',
  'world',
  'domination'],
 ['james',
  'bond',
  'descends',
  'mystery',
  'tries',
  'stop',
  'mysterious',
  'organization',
  'eliminating',
  'country',
  'valuable',
  'resource',
  'still',
  'tries',
  'seek',
  'revenge',
  'death',
  'love'],
 ['earth',
  'mightiest',
  'heroes',
  'must',
  'come',
  'together',
  'learn',
  'fight',
  'team',
  'stop',
  'mischievous',
  'loki',
  'alien',
  'army',
  'enslaving',
  'humanity'],
 ['jack',
  'sparrow',
  'races',
  'recover',
  'heart',
  'davy',
  'jones',
  'avoid',
  'enslaving',
  'soul',
  'jones',
  'service',
  'friends',
  'foes',
  'seek',
  'heart',
  'agenda',
  'well'],
 ['clark',
  'kent',
  'one',
  'last',
  'extinguished',
  'race',
  'disguised',
  'unremarkable',
  'human',
  'forced',
  'reveal',
  'identity',
  'earth',
  'invaded',
  'army',
  'survivors',
  'threaten',
  'bring',
  'planet',
  'brink',
  'destruction'],
 ['pevensie',
  'siblings',
  'return',
  'narnia',
  'enlisted',
  'help',
  'ward',
  'evil',
  'king',
  'restore',
  'rightful',
  'heir',
  'land',
  'throne',
  'prince',
  'caspian'],
 ['peter',
  'parker',
  'bitten',
  'genetically',
  'altered',
  'spider',
  'gains',
  'newfound',
  'spider',
  'like',
  'powers',
  'ventures',
  'solve',
  'mystery',
  'parent',
  'mysterious',
  'death'],
 ['new',
  'theme',
  'park',
  'built',
  'original',
  'site',
  'jurassic',
  'park',
  'creates',
  'genetically',
  'modified',
  'hybrid',
  'dinosaur',
  'escapes',
  'containment',
  'goes',
  'killing',
  'spree']]

In [18]:
df['Clean_plot'] = plot

In [19]:
df['Clean_plot']

0     [paraplegic, marine, dispatched, moon, pandora...
1     [captain, barbossa, turner, elizabeth, swann, ...
2     [cryptic, message, bond, past, sends, trail, u...
3     [eight, years, joker, reign, anarchy, dark, kn...
4     [native, american, warrior, tonto, recounts, u...
5     [transported, barsoom, civil, war, vet, discov...
6     [magically, long, haired, rapunzel, spent, ent...
7     [strange, black, entity, another, world, bonds...
8     [tony, stark, bruce, banner, try, jump, start,...
9     [political, interference, avengers, activities...
10    [fearing, actions, superman, left, unchecked, ...
11    [reluctant, hobbit, bilbo, baggins, sets, lone...
12    [harry, potter, begins, sixth, year, hogwarts,...
13    [dwarves, along, bilbo, baggins, gandalf, grey...
14    [bilbo, company, forced, engage, war, array, c...
15    [jack, sparrow, barbossa, embark, quest, find,...
16    [superman, reappears, long, absence, challenge...
17    [james, bond, descends, mystery, tries, stop, ...
18    [earth, mightiest, heroes, must, come, togethe...
19    [jack, sparrow, races, recover, heart, davy, j...
20    [clark, kent, one, last, extinguished, race, d...
21    [pevensie, siblings, return, narnia, enlisted,...
22    [peter, parker, bitten, genetically, altered, ...
23    [new, theme, park, built, original, site, jura...
Name: Clean_plot, dtype: object

In [20]:
df.head()

,Unnamed: 0,Title,Year,Rated,Released,Runtime,Genre,Director,Writer,Actors,Plot,Language,Country,Awards,Poster,Ratings.Source,Ratings.Value,Metascore,imdbRating,imdbVotes,imdbID,Type,tomatoMeter,tomatoImage,tomatoRating,tomatoReviews,tomatoFresh,tomatoRotten,tomatoConsensus,tomatoUserMeter,tomatoUserRating,tomatoUserReviews,tomatoURL,DVD,BoxOffice,Production,Website,Response,Clean_plot
0,1,Avatar,2009,PG-13,18 Dec 2009,162 min,"Action, Adventure, Fantasy",James Cameron,James Cameron,"Sam Worthington, Zoe Saldana, Sigourney Weaver...",A paraplegic marine dispatched to the moon Pan...,"English, Spanish","UK, USA",Won 3 Oscars. Another 86 wins & 128 nominations.,https://images-na.ssl-images-amazon.com/images...,Internet Movie Database,7.8/10,83,7.8,"939,525",tt0499549,movie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/avatar/,22 Apr 2010,"$749,700,000",20th Century Fox,http://www.avatarmovie.com/,True,"[paraplegic, marine, dispatched, moon, pandora..."
1,2,Pirates of the Caribbean: At World's End,2007,PG-13,25 May 2007,169 min,"Action, Adventure, Fantasy",Gore Verbinski,"Ted Elliott, Terry Rossio, Ted Elliott (charac...","Johnny Depp, Geoffrey Rush, Orlando Bloom, Kei...","Captain Barbossa, Will Turner and Elizabeth Sw...",English,USA,Nominated for 2 Oscars. Another 20 wins & 44 n...,https://images-na.ssl-images-amazon.com/images...,Internet Movie Database,7.1/10,50,7.1,"506,076",tt0449088,movie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/pirates_of_the...,04 Dec 2007,"$309,404,152",Buena Vista,http://disney.go.com/disneypictures/pirates/at...,True,"[captain, barbossa, turner, elizabeth, swann, ..."
2,3,Spectre,2015,PG-13,06 Nov 2015,148 min,"Action, Adventure, Thriller",Sam Mendes,"John Logan (screenplay), Neal Purvis (screenpl...","Daniel Craig, Christoph Waltz, Léa Seydoux, Ra...",A cryptic message from Bond's past sends him o...,"English, Spanish, Italian, German, French","UK, USA",Won 1 Oscar. Another 7 wins & 30 nominations.,https://images-na.ssl-images-amazon.com/images...,Internet Movie Database,6.8/10,60,6.8,"311,366",tt2379713,movie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/spectre_2015/,09 Feb 2016,"$208,777,731",Sony Pictures,http://www.007.com/,True,"[cryptic, message, bond, past, sends, trail, u..."
3,4,The Dark Knight Rises,2012,PG-13,20 Jul 2012,164 min,"Action, Thriller",Christopher Nolan,"Jonathan Nolan (screenplay), Christopher Nolan...","Christian Bale, Gary Oldman, Tom Hardy, Joseph...",Eight years after the Joker's reign of anarchy...,"English, Arabic","UK, USA",Nominated for 1 BAFTA Film Award. Another 38 w...,https://images-na.ssl-images-amazon.com/images...,Internet Movie Database,8.5/10,78,8.5,"1,228,378",tt1345836,movie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/the_dark_knigh...,03 Dec 2012,"$448,130,642",Warner Bros. Pictures,http://www.thedarkknightrises.com/,True,"[eight, years, joker, reign, anarchy, dark, kn..."
4,5,The Lone Ranger,2013,PG-13,03 Jul 2013,150 min,"Action, Adventure, Western",Gore Verbinski,"Justin Haythe (screenplay), Ted Elliott (scree...","Johnny Depp, Armie Hammer, William Fichtner, T...",Native American warrior Tonto recounts the unt...,"English, North American Indian",USA,Nominated for 2 Oscars. Another 4 wins & 17 no...,https://images-na.ssl-images-amazon.com/images...,Internet Movie Database,6.5/10,37,6.5,"191,532",tt1210819,movie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/the_lone_ranger/,17 Dec 2013,"$89,289,910",Walt Disney Pictures,http://disney.go.com/the-lone-ranger/,True,"[native, american, warrior, tonto, recounts, u..."

In [34]:
df['Genre'] = df['Genre'].apply(lambda x: [i.strip() for i in x] if isinstance(x, list) else [i.strip() for i in x.split(',')]) 
df['Actors'] = df['Actors'].apply(lambda x: [i.strip() for i in x[:4]] if isinstance(x, list) else [i.strip() for i in x.split(',')[:4]])
df['Director'] = df['Director'].apply(lambda x: [i.strip() for i in x] if isinstance(x, list) else [i.strip() for i in x.split(',')])

In [35]:
df['Genre'][2]

['Action', 'Adventure', 'Thriller']

In [38]:
columns = ['Clean_plot', 'Genre', 'Actors', 'Director']
l = []
for i in range (len(df)):
    words = ''
    for col in columns:
        words += ' '.join(df[col][i]) + ' '
        l.append(words)
        l

In [45]:
df['Clean_input'] = l[:len(df)]
df = df[['Title', 'Clean_input']]
df.head()

,Title,Clean_input
0,Avatar,paraplegic marine dispatched moon pandora uniq...
1,Pirates of the Caribbean: At World's End,paraplegic marine dispatched moon pandora uniq...
2,Spectre,paraplegic marine dispatched moon pandora uniq...
3,The Dark Knight Rises,paraplegic marine dispatched moon pandora uniq...
4,The Lone Ranger,captain barbossa turner elizabeth swann must s...

In [ ]:
## Features Extraction:

In [49]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

tfidf = TfidfVectorizer()
features = tfidf.fit_transform(df['Clean_input'])

In [50]:
# Create cosine similarity matrix

In [ ]:
pip ins

In [52]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_sin = cosine_similarity(features, features)
print(cosine_sin)

[[1.         0.9591629  0.73866027 0.69401064 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.9591629  1.         0.7701093  0.72355868 0.         0.06750196
  0.05582922 0.05358776 0.         0.0249663  0.02117353 0.02043366
  0.         0.01216064 0.00984056 0.00937698 0.         0.03408306
  0.02657022 0.02521336 0.         0.02655528 0.02211705 0.0211091 ]
 [0.73866027 0.7701093  1.         0.93955323 0.         0.05198389
  0.0429946  0.04126843 0.         0.01922678 0.01630594 0.04971394
  0.         0.00936502 0.0075783  0.0072213  0.         0.02624768
  0.02046198 0.01941704 0.         0.02045047 0.01703254 0.01625631]
 [0.69401064 0.72355868 0.93955323 1.         0.         0.04884163
  0.04039572 0.03877389 0.         0.01806458 0.01532029 0.04670889
  0.         0.00879894 0.00712022 0.00678479 0.         0.02466109
  0.01922512 0.01824334 0.         0.01921431 0.01600298 0.01527367]
 [0.         0.         0.         0.         1.         0.97110669
  0.80317855 0.77093214 0.         0.         0.         0.
  0.02716645 0.02658621 0.02151392 0.02050042 0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.06750196 0.05198389 0.04884163 0.97110669 1.
  0.8270755  0.79386966 0.         0.02106421 0.01786423 0.01723999
  0.02638152 0.03607804 0.02919485 0.02781951 0.         0.02875607
  0.02241745 0.02127266 0.         0.02240484 0.01866028 0.01780986]
 [0.         0.05582922 0.0429946  0.04039572 0.80317855 0.8270755
  1.         0.9598515  0.         0.01742169 0.01477507 0.01425878
  0.02181951 0.02983927 0.02414634 0.02300883 0.         0.02378344
  0.08649056 0.08207373 0.         0.0185305  0.01543346 0.0147301 ]
 [0.         0.05358776 0.04126843 0.03877389 0.77093214 0.79386966
  0.9598515  1.         0.         0.01672223 0.01418187 0.01368631
  0.02094349 0.02864126 0.0231769  0.02208506 0.         0.02282857
  0.08301809 0.16727289 0.         0.01778653 0.01481383 0.01413871]
 [0.         0.         0.         0.         0.         0.
  0.         0.         1.         0.97748956 0.82899397 0.80002608
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.0249663  0.01922678 0.01806458 0.         0.02106421
  0.01742169 0.01672223 0.97748956 1.         0.84808473 0.81844974
  0.         0.03792381 0.03068846 0.02924276 0.         0.02542289
  0.01981899 0.01880689 0.         0.01980785 0.01649732 0.01574548]
 [0.         0.02117353 0.01630594 0.01532029 0.         0.01786423
  0.01477507 0.01418187 0.82899397 0.84808473 1.         0.96505658
  0.         0.0321626  0.02602642 0.02480034 0.         0.02156077
  0.01680818 0.01594984 0.         0.01679873 0.01399113 0.0133535 ]
 [0.         0.02043366 0.04971394 0.04670889 0.         0.01723999
  0.01425878 0.01368631 0.80002608 0.81844974 0.96505658 1.
  0.         0.03103873 0.02511696 0.02393373 0.         0.02080736
  0.01622085 0.0153925  0.         0.01621173 0.01350223 0.01288689]
 [0.         0.         0.         0.         0.02716645 0.02638152
  0.02181951 0.02094349 0.         0.         0.         0.
  1.         0.9786411  0.79192973 0.75462281 0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.01216064 0.00936502 0.00879894 0.02658621 0.03607804
  0.02983927 0.02864126 0.         0.03792381 0.0321626  0.03103873
  0.9786411  1.         0.80921364 0.77109249 0.         0.01238304
  0.00965348 0.00916051 0.         0.00964805 0.00803555 0.00766935]
 [0.         0.00984056 0.0075783  0.00712022 0.02151392 0.02919485
  0.02414634 0.0231769  0.         0.03068846 0.02602642 0.02511696
  0.79192973 0.80921364 1.         0.95289112 0.         0.01002052
  0.04056121 0.03848987 0.         0.00780734 0.00650248 0.00620614]
 [0.         0.00937698 0.0072213  0.00678479 0.02050042 0.02781951
  0.02300883 0.02208506 0.         0.02924276 0.02480034 0.02393373
  0.75462281 0.77109249 0.95289112 1.         0.         0.00954847
  0.03865042 0.03667665 0.         0.00743954 0.00619616 0.00591378]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         1.         0.94358621
  0.73559408 0.69802943 0.         0.         0.         0.        ]
 [0.         0.03408306 0.02624768 0.02466109 0.         0.02875607
  0.02378344 0.02282857 0.         0.02542289 0.02156077 0.02080736
  0.         0.01238304 0.01002052 0.00954847 0.94358621 1.
  0.77957273 0.73976222 0.         0.02704094 0.02252153 0.02149515]
 [0.         0.02657022 0.02046198 0.01922512 0.         0.02241745
  0.08649056 0.08301809 0.         0.01981899 0.01680818 0.01622085
  0.         0.00965348 0.04056121 0.03865042 0.73559408 0.77957273
  1.         0.9489329  0.         0.02108038 0.01755717 0.01675703]
 [0.         0.02521336 0.01941704 0.01824334 0.         0.02127266
  0.08207373 0.16727289 0.         0.01880689 0.01594984 0.0153925
  0.         0.00916051 0.03848987 0.03667665 0.69802943 0.73976222
  0.9489329  1.         0.         0.02000386 0.01666058 0.0159013 ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         1.         0.94231012 0.78481994 0.749053  ]
 [0.         0.02655528 0.02045047 0.01921431 0.         0.02240484
  0.0185305  0.01778653 0.         0.01980785 0.01679873 0.01621173
  0.         0.00964805 0.00780734 0.00743954 0.         0.02704094
  0.02108038 0.02000386 0.94231012 1.         0.83286799 0.79491134]
 [0.         0.02211705 0.01703254 0.01600298 0.         0.01866028
  0.01543346 0.01481383 0.         0.01649732 0.01399113 0.01350223
  0.         0.00803555 0.00650248 0.00619616 0.         0.02252153
  0.01755717 0.01666058 0.78481994 0.83286799 1.         0.95442657]
 [0.         0.0211091  0.01625631 0.01527367 0.         0.01780986
  0.0147301  0.01413871 0.         0.01574548 0.0133535  0.01288689
  0.         0.00766935 0.00620614 0.00591378 0.         0.02149515
  0.01675703 0.0159013  0.749053   0.79491134 0.95442657 1.        ]]

In [55]:
# Movie Recomandation

index = pd.Series(df['Title'])
index.head()

0                                      Avatar
1    Pirates of the Caribbean: At World's End
2                                     Spectre
3                       The Dark Knight Rises
4                             The Lone Ranger
Name: Title, dtype: object

In [67]:
def recommend_movies(title, cosine_sin):
    movies = []
    
    # Get index of the movie
    idx = df[df['Title'] == title].index[0]
    print(f"Index of '{title}':", idx)
    
    # Get similarity scores and sort them
    score = pd.Series(cosine_sin[idx]).sort_values(ascending=False)
    top10 = list(score.iloc[1:11].index)  # Skip the first (same movie)
    print("Top 10 similar movie indices:", top10)
    
    # Fetch movie titles
    for i in top10:
        movies.append(df['Title'][i])
    
    return movies

In [70]:
recommend_movies( "Pirates of the Caribbean: At World's End", cosine_sin)

Index of 'Pirates of the Caribbean: At World's End': 1
Top 10 similar movie indices: [0, 2, 3, 5, 6, 7, 17, 18, 21, 19]

['Avatar',
 'Spectre',
 'The Dark Knight Rises',
 'John Carter',
 'Tangled',
 'Spider-Man 3',
 'Quantum of Solace',
 'The Avengers',
 'The Chronicles of Narnia: Prince Caspian',
 "Pirates of the Caribbean: Dead Man's Chest"]

In [97]:
index [index == 'The Lone Ranger'].index[0]

np.int64(4)

In [109]:
 score = pd.Series(cosine_sin[5]).sort_values(ascending=False)

In [110]:
recommend_movies('The Chronicles of Narnia: Prince Caspian', cosine_sin)

Index of 'The Chronicles of Narnia: Prince Caspian': 21
Top 10 similar movie indices: [20, 22, 23, 17, 1, 5, 18, 2, 19, 9]

['Man of Steel',
 'The Amazing Spider-Man',
 'Jurassic World',
 'Quantum of Solace',
 "Pirates of the Caribbean: At World's End",
 'John Carter',
 'The Avengers',
 'Spectre',
 "Pirates of the Caribbean: Dead Man's Chest",
 'Captain America: Civil War']

In [112]:
len(df)

24